Making hw 4
Hroom1x/prep-2022-01 pull request #3
Opened 2022-04-20 10:33 UTC by Hroom1x

Большая часть функционала выполнена. Осталось пофиксить тесты

2022-04-22 20:44 UTC, ITesserakt commented
Не подключен Github CI

2022-04-22 20:56 UTC, ITesserakt commented
Фиксишь CI - я проверяю
![image](https://user-images.githubusercontent.com/37984459/164792315-f29eb831-1b52-4851-9925-c2b850283fa8.png)

2022-06-06 22:40 UTC, ITesserakt requested changes
Идешь на 1 балл!

2022-06-06 22:40 UTC, ITesserakt commented on CPPLINT.cfg
> +linelength=1100
??

2022-06-06 22:40 UTC, ITesserakt commented on project/src/parser.c
> +        value = realloc(value, length);
Плохо делать a = realloc(a) + value may be null

2022-06-06 22:40 UTC, ITesserakt commented on project/src/parser.c
> +    value = realloc(value, length);
То же

2022-06-06 22:40 UTC, ITesserakt commented on project/src/parser.c
> +    char *value = calloc(length + 1, sizeof(char));
value may be null

2022-06-06 22:40 UTC, ITesserakt commented on project/src/parser.c
> +    snprintf(result, FORMAT_STRING_MAX_SIZE,
Тут можно и обычный printf

2022-06-08 16:43 UTC, Hroom1x commented on CPPLINT.cfg
> +linelength=1100
220

2022-06-08 16:44 UTC, Hroom1x commented on project/src/parser.c
> +    snprintf(result, FORMAT_STRING_MAX_SIZE,
result - возвращаемое значение функции

2022-06-08 16:45 UTC, merged

2022-06-15 13:17 UTC, ITesserakt commented
Ну вот зачем было мержить